Update callbacks when component receives new props
leoasis/react-sound pull request #16
Opened 2016-09-22 02:26 UTC by jamesdphillips

2016-09-23 20:10 UTC, leoasis commented
Hey! First of all thanks for the PR and for finding this useful!

Regarding the change, I think a better solution for this would be to hold on the instance reference and whenever the sound calls an event, use that instance to get the latest props, in here https://github.com/leoasis/react-sound/blob/master/src/index.js#L124.

Basically the idea would be to do this:

```js
    const instance = this;

    this.stopCreatingSound = createSound({
      url: this.props.url,
      volume: props.volume,
      whileloading() {
        instance.props.onLoading(this);
      },
      whileplaying() {
        instance.props.onPlaying(this);
      },
      onfinish() {
        instance.props.onFinishedPlaying();
      }
    }, sound => {
      this.sound = sound;
      callback(sound);
    });
```

Would you like to change the PR to do something like this?

2016-09-24 03:39 UTC, jamesdphillips commented
That seems like a great idea. I'll take a crack at it next week 👍

2016-09-26 22:55 UTC, leoasis commented
Awesome! Thanks for contributing! 🎉

2017-02-01 14:30 UTC, leoasis commented
Hey @jamesdphillips, were you able to make this happen? Willing to send a PR? 😄

2017-09-28 09:04 UTC, peinguin commented on src/index.js
> +      sound.options.whileloading = () => this.props.onLoading(this) || null;
why not just
sound.options.onfinish = this.props.onFinishedPlaying
is "this" really needed in arguments?

2017-09-28 09:07 UTC, peinguin commented on src/index.js
> +      sound.options.whileloading = () => this.props.onLoading(this) || null;
I saw the code.
It will be wrong this.
Use sound instead of this.

2017-09-28 09:07 UTC, peinguin requested changes
It will be wrong this.
Use sound instead of this.

2017-12-26 15:33 UTC, closed without merging