Fix for position not working on mount
leoasis/react-sound pull request #34
Opened 2017-07-10 01:16 UTC by C-Higgins

#32

2017-07-11 17:25 UTC, leoasis requested changes
Awesome! thanks for the contribution!

Just made a comment for an unrelated change, but other than that, 👍

2017-07-11 17:25 UTC, leoasis commented on src/index.js
> +  if (process.env.NODE_ENV === 'production') {
Can we remove this? This doesn't belong to this particular fix, and also I believe we can do better, there's a discussion for this in https://github.com/leoasis/react-sound/issues/13#issuecomment-263689258

2017-07-14 13:43 UTC, C-Higgins commented
Updated

2017-07-14 19:48 UTC, eveningkid commented
Can't wait for the update, just got into the same issue! Thanks a lot guys. :)

2017-07-14 20:48 UTC, leoasis approved these changes

2017-07-14 20:48 UTC, merged

2017-07-14 20:53 UTC, leoasis commented
Merged and published version 0.6.2 with this. Thanks for helping! https://github.com/leoasis/react-sound/releases/tag/v0.6.2